services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: fastpoke-app
    working_dir: /app
    volumes:
      - .:/app:cached
    ports:
      - ${APP_PORT:-8000}:80
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - path: ./.env
        required: false
    environment:
      APP_ENV: ${APP_ENV:-dev}
    tty: true

  redis:
    image: redis:8
    container_name: fastpoke-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  mailpit:
    image: axllent/mailpit
    container_name: fastpoke-mailpit
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: fastpoke-postgres
    env_file:
      - path: ./.env
        required: false
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  postgres-data:
